---
title: "Assignment3"
author: "FNU Anirudh"
date: "September 30, 2015"
output: word_document
---

Question 1

```{r,eval=TRUE}
#1 a)
library(noncensus)
data(counties)
library(car)

completeCounties<-counties[complete.cases(counties),]
stateAggre<-with(counties, aggregate(counties$state, list(counties$state), FUN=unique))
med<-with(counties, aggregate(counties$population, list(counties$state),FUN=median))
median<-as.vector(med$x)
state<-as.matrix(stateAggre$x)
stateMedianCombine <- cbind(median, state)
completeMedian<-stateMedianCombine[complete.cases(stateMedianCombine),]

quantiles<-with(counties, aggregate(counties$population, list(counties$state),FUN=quantile, na.rm = TRUE ))

completeQuantiles <- quantiles[complete.cases(quantiles),]
Forths<-matrix()
for(i in 1:nrow(quantiles$x)){
  Forths<-c(Forths,(quantiles$x[i,'75%'] - quantiles$x[i,'25%']))
}
transForths<- t(t(Forths))
completeForths <- transForths[complete.cases(transForths)]
matrixMH<- cbind(completeMedian,completeForths)
mX<-as.numeric(matrixMH[-c(8),1])
mY<-as.numeric(matrixMH[-c(8),3])
matrixMH2 <- cbind(mX,mY)

#Level vs Spread Plot
spreadLevelPlot(matrixMH2,by=matrixMH[-c(8),2],main="Spread Vs Level Plot")

#Scatter plot with log transform
#scatterplotMatrix(log(matrixMH))
#abline(lm(log(matrixMH[-c(7),1])~log(matrixMH[-c(7),2])))

#matrixMHState<-cbind(matrixMH,as.matrix(stateAggre$x))


plot(log(mX)~log(mY))
abline(mod<-lm(log(mX)~log(mY)))
slope<- coef(mod)[2]
slope

# Equation of line that fits is y=0.93x+c where Slope m=0.93
# Substituting (10,9.5) we get c=0.2
# Equation of line is y=0.93x+0.2
# b)
#The slope of the line is is 0.93, so p = 1-b = 1-0.93 = 0.07 = 0 (approx)
#T(x) = log(x)
boxplot(log(matrixMH2),main="Box Plot")
# c)
# Without Transform
boxplot(completeCounties$population~completeCounties$state,main="Box Plot
        without Transform")
# After Transform
boxplot((log(completeCounties$population)~completeCounties$state),
main="Box Plot after Transform")

# d)
source("C:/Users/lenovo/Documents/lvalprogs.R")
CAsubset<- completeCounties[completeCounties["state"] == "CA",]
letterValues <- lval(CAsubset$population)
#root<-letterValues^(1/30)
VectorXL <- as.vector(letterValues[,2])
VectorXU <- as.vector(letterValues[,3])

M <- letterValues[1,"Lower"] 

Y<- (VectorXL + VectorXU)/2 - M
X<- ((VectorXL-M)^2 + (VectorXU - M)^2) / (4*M)
letterValue<-c("M","F","E","D","C","B");
p<- (1-Y/X)
p
Table<- data.frame(letterValue,VectorXL,VectorXU,X,Y,p)

# e)
plot(Y~X)
abline(mod<-lm(Y~X))
slope <- coef(mod)[2]
slope
# b=0 after rounding slope to nearest 0.5
# Power transform p= 1-0= 1.

# f)
# T(x) = log(x), then T'(x) = 1/x i.e. z = x0*(1 + log(x) - log(x0)) = 427761.5 * log(x) - 5118731
#a = 427761.5, b = - 5118731

```

Question 2

```{r,eval=TRUE}
data = read.table("ceo.txt", header = T)
# a) Number of CEO's and Highest Paid CEO's
n=length(data$TotalCompensation)
max_sal=max(data$TotalCompensation)
print(max_sal)
print(n)
boxplot(data,horizontal = TRUE,col="red")
# There are many Outliers which can be said to be unusual values.
# b) Graphical Display for Data
hist(data[,1])
# Distribution is skewed to the right and I would like to transform the 
#data.

# c) Cube root transform will be more appropriate as it will make data
#symmetric and can resemble normal distribution.

# d) We need to remove low valued data also few Ceo with salary 0 as it 
# affect mean.
summary(data)
clear_data<- data[data[,1]> 10000,]
summary(clear_data)
# e) 
hist(data[,1])
# Square root Transform
hist(sqrt(data[,1]))
# Cube root Transform
hist(data[,1]^(1/3))
# Log Transform
hist(log(data[,1]))

# Transform after removing outliers
hist(clear_data)
hist(sqrt(clear_data))
hist(clear_data^(1/3))
hist(log(clear_data))
# As you can see data has become more symmetric when cube root transform
#is applied.

# f) I would choose cube root transform as it makes data symmetric and 
#less skewed compared to log or square root transform

```

Question 3

```{r, eval=TRUE}
#3 a)
LVhouseHold_data <- cbind(c(rep(0, 10)),c(0, 2412, 1788, 1517, 1248, 963.5, 727.5, 579,345,114),c(3480,3678,4115.5,4400.5,4799,4978.75,5241,5394.5,5510.25,5494),c(0,4944,6443,7284,8350,8994,9754.5,10210,10675.5,10874));

#x0 = 3480, z = a*x^(1/3) + b, dz/dx = (1/3)a*x^(-2/3), Now, at x0 = 3480 , a = 688.9284 , b = -6960 Hence, z = 688.9284* x^(1/3) - 6960

# b)
Transformed_value <- 688.9284* (LVhouseHold_data)^(1/3) - 6960
Transformed_value

# c)
# Mids are almost same as compared to data in table 4-5.But mids are very
# far seperated compared to log, square root, fourth root transform,
# By Comparing 25th and 75th quantiles, it has moved away from  orignal
# data. Spread has increased compared to other transforms hence we can
# easily identify any outliers.
```


